


= SHELL SCRIPTING

Shell is an interface b/w user and the os(Operating System)
----
cat /etc/shells -> its going to give all shell types in your system
----
sh -> old +
korn shell -> (ksh) +
Bourne-Again Shell (bash) +
c shell -> (csh) +
Tiny shell -> (tcsh) +
z shell ->(zsh) +

=== How to change shell type?

Using this commands we can change shell type
----
cat /bin/sh
cat /bin/bash
cat /bin/sh
----

=== How to check current shell

----
echo $0
ps -p $$
echo $SHELL
----

=== shebang line
----
#!/bin/bash (shebang line)
----
when we mention this it going to use bash or else it use default shell

=== How to run dbug mode in perticular line in shell scripting

ex:

----
#!/bin/bash
echo "Hello"
set -x
echo "gm/ge/gn"
set +x
echo "Today Date is"
date
echo "Welcome to shell scripting"
----

`set -x` -> Is the starting point, `set +x` -> Is ending point for dbuging


=== How to comments line in Shell Scripting

Single line comment -> // (forward slash) +
Multiline comment -> /* -> starting line, /** -> ending line +

Documentation reloaded comment -> / ** -> starting line , */ -> ending line


=== Variables

A Variables is a character string to which we assign a value, the value assigned colud be a number, text, filename,device or any other type data

==== Types of variables

- user define variables
- system variables

=== How to print system define varibales to disply

----
env
or
printenv
----

=== command line arguments

During shell scripting execution, value passing through command prompt is called as command line argument

ex:

----
script.sh arg1 arg2 arg3
----

==== echo $# -> it will show number of argument as executed
==== echo $* -> All the arguments as a one string
==== echo $@ -> All the arguments , each arguments as a one string
==== echo $$ -> It will give process id [PID]
==== echo $? -> Previous command execution status, if command is execution successful `0`, and id command is unsuccessful `1`


=== Comparison Operators in Shell Scripting

[cols="1,2", options="header"]
|===
| Symbol  | Description

| `-eq`
| Equal to (`==`)

| `-ne`
| Not equal to (`!=`)

| `-lt`
| Less than (`<`)

| `-le`
| Less than or equal to (`< =`)

| `-gt`
| Greater than (`>`)

| `-ge`
| Greater than or equal to (`>=`)
|===

=== String

String is a zero or more chartreuse enclosed in  single or double quotes. we use single or double quotation to define a string






#!/bin/bash - shebang (octa trap)
----
aws s3 ls | cut -d ' ' -f 3 | grep -E www[.]

----

how to run shell script

give permission

----
./script.abc

or

bash script.abc

or

#debug

#`set -x` should be mention in script

bash script.abc
----

awk command,
grep command,
egrep command,
varibale declaration,


=== To retrieve vpc data information

----
aws ec2 describe-vpcs --region us-east-1

or

aws ec2 describe-vpcs --region us-east-1 | jq

or

aws ec2 describe-vpcs --region us-east-1 | jq ".Vpcs[]"


#how to get only vpc id
aws ec2 describe-vpcs --region us-east-1 | jq ".Vpcs[].VpcID"


#how to get only vpc id and how to remove ""
aws ec2 describe-vpcs --region us-east-1 | jq ".Vpcs[].VpcID" -r

or

#how to get only vpc id and how to remove "" and how to
aws ec2 describe-vpcs --region us-east-1 | jq ".Vpcs[].VpcID" | tr -d '"'


#how to get only vpc id and how to remove "" and how to make it uppercase
aws ec2 describe-vpcs --region us-east-1 | jq ".Vpcs[].VpcID" | tr '[:]'


----



Using script how to achive this
create file `script.sh`
and give necessary permissions
----
#!/bin/bash

REGION='us-east-1'
aws ec2 describe-vpcs --region ${REGION} | jq ".Vpcs[].VpcID" | tr '[:]'
----
how to pass as variable

----
#!/bin/bash
REGION=$1
aws ec2 describe-vpcs --region ${REGION} | jq ".Vpcs[].VpcID" | tr '[:]'
----

Run this command

----
script.sh us-east-1
----




==== Error code and Exit codes



