= EC2 Concepts

== What is Elastic IP?

An Elastic IP address is a reserved public IP address that you can assign to any EC2 instance in a particular region, until you choose to release it. You can mask the failure of an instance or software by rapidly remapping the address to another instance in your account. Elastic IPs are also known as Static IPs. They are public IPv4 addresses, routable over the internet.

== What is KeyPairs?

A key pair, consisting of a public key and private key, is a set of security credentials that you use to prove your identity when connecting to an Amazon EC2 instance. Amazon EC2 stores the public key on your instance, and you store the private key.

=== Difference between .pem & .ppk

- PEM (Privacy Enhanced Mail) is a base64 container format for encoding keys and certificates. The .pem file is downloaded from AWS when you create your key-pair. This is only a one-time download and cannot be downloaded again.
- PPK (PuTTY Private Key) is used by the Windows SSH client PuTTY, which does not support the .pem format. Therefore, you need to convert the .pem file to .ppk format using PuTTYgen.

== What is SnapShots?

Snapshots can be used to create a backup of critical workloads, such as a large database or a file system that spans across multiple EBS volumes. A snapshot is a point-in-time copy of an Amazon EBS volume with limited storage and recovery options. Snapshots are a common way to protect data and systems.

== What is Load Balancer?

A load balancer acts as the "traffic cop" sitting in front of your servers and routing client requests across all servers capable of fulfilling those requests in a manner that maximizes speed and capacity utilization and ensures that no one server is overworked, which could degrade performance.

== What is Security Groups?

A security group acts as a virtual firewall for your EC2 instances to control incoming and outgoing traffic. Inbound rules control the incoming traffic to your instance, and outbound rules control the outgoing traffic from your instance.

== What are Volumes?

EC2 Volumes (called Elastic Block Storage by Amazon) are essentially disk images that can be mounted on any system running on EC2, and continue to exist even if the system they were attached to is deleted.

(or)

An Amazon EBS volume is a durable, block-level storage device that you can attach to your instances. After you attach a volume to an instance, you can use it as you would use a physical hard drive. EBS volumes are flexible.

=== Types of EBS Volumes

1. General Purpose SSD (gp2) Volumes - balances performance and price; used for low-latency app, dev, and test environments.
2. Provisioned IOPS SSD (io1) Volumes - low-latency or high-throughput applications; used for large databases and critical business applications.
3. Throughput Optimized HDD (st1) Volumes - low-cost; used for log processing, data warehouses, and streaming workloads.
4. Cold HDD (sc1) Volumes - low-cost; used as a cheap storage solution.

== What do you mean by Tags? Why do we require it?

A tag is a label consisting of a user-defined key and value. Tags can help you manage, identify, organize, search for, and filter resources.

== What is the difference between public IP and private IP?

[cols="1,1"]
|===
|Public IP |Private IP

|The scope of Public IP is global. |The scope of Private IP is local.

|It is used to communicate outside the network. |It is used to communicate within the network.

|Public IP may differ in a uniform or non-uniform manner. |Private IP addresses of the systems connected in a network differ in a uniform manner.

|It is used to get internet service. |It works only on LAN.

|Public IP is available free of cost. |Private IP is available free of cost.

|Public IP uses a numeric code that is unique and cannot be used by others. |Private IP uses a numeric code that is not unique and can be used again.

|Public IP address has no security and is subjected to attack. |Private IP addresses are secure.

|Range: Besides private IP addresses, the rest are public. |Ex: 10.0.0.0 – 10.255.255.255, 172.16.0.0 – 172.31.255.255, 192.168.0.0 – 192.168.255.255
|===

== List out the Private IPs

* Class A – 10.0.0.0 to 10.255.255.255
* Class B – 172.16.0.0 to 172.31.255.255
* Class C – 192.168.0.0 to 192.168.255.255

== How do you change the instance type of a running instance?

No, that is not possible while running. We need to stop the instance and then change the instance type.
Select the instance → Action → Instance settings → Change instance type → Select as per requirement.

== How do you attach an IAM role on a running instance?

Yes, we can attach or detach an IAM role while running but after modification, the instance needs to be rebooted.
Select the instance → Action → Security → Modify IAM role → Select as per requirement.

== What is Termination Protection?

Termination protection prevents an instance from accidental termination. By default, this option is disabled for EC2 instances. Enable this option to protect your instance from any unintentional termination.
Select the instance → Choose Actions → Instance Settings → Change Termination Protection → Choose Yes → Disable.

== How do you bootstrap an instance with a set of commands?

1. `yum install httpd* -y` → First, we need to install httpd in the instance
2. `service httpd status` → Inactive → `systemctl start httpd.service`
3. `cd /var/www/html` → Create a file with content and save it as (.html)
4. `systemctl restart httpd.service`
5. Go to Browser → Search your instance public IP

== How do you edit the User Data?

Yes, we can change our user data, but it is not possible while the instance is running.
Stop instance → Select the instance → Action → Instance settings → Edit user data → Modify user data → Save and start instance.

== How do you create an image from a running/stopped instance?

Yes, we can create Amazon Machine Images (AMIs) from either running or stopped instances.
Select the instance → Action → Images and templates → Create AMI

- If the image is created on a running instance, the file system integrity on the created image cannot be guaranteed. If you're confident that your instance is in a consistent state appropriate for image creation, you can tell Amazon EC2 not to power down and reboot the instance. To do this, for No reboot, select the Enable checkbox.

== How do you get the System Log from an instance?

Yes, we can get the system log in the instance.
Select the instance → Action → Monitor and troubleshoot → Get system log → Download.

== Will I be able to choose a different AMI while the instance is running?

No, replacing the "AMI" is literally the process of creating a new server. If IP address consistency is a concern, then you should be using an Elastic IP.

== What is the difference between I/B & O/B rules in Security Groups?

[cols="1,1"]
|===
|Inbound Security Group |Outbound Security Group

|Inbound rules control the incoming traffic to your instance. |Outbound rules control the outgoing traffic from your instance.

|Inbound traffic that's allowed to reach the resources that are associated with the security group. |Outbound rules that allow all outbound traffic from the resource (O/B rule max. 60).

|The number of inbound rules per security group in Amazon is 60. |You can remove the rule and add outbound rules that allow specific outbound traffic only.

|If your security group has no outbound rules, no outbound traffic is allowed. |
|===

== List the number of Ports

|===
|Port |Service
|20,21 |File Transfer Protocol (FTP) Data Transfer
|22 |Secure Shell (SSH)
|53 |Domain Name System (DNS) service
|123 |Network Time Protocol (NTP)
|443 |HTTP Secure (HTTPS) HTTP over TLS/SSL
|110 |Post Office Protocol (POP3) used by e-mail clients to retrieve e-mail from a server
|25 |Simple Mail Transfer Protocol (SMTP) E-mail Routing
|3389 |Remote Desktop Protocol
|23 |Telnet
|69 |Trivial File Transfer Protocol (TFTP)
|===

== What is Subnet? Why do we require Subnet? What is the difference between Public and Private Subnet?

A subnetwork or subnet is a logical subdivision of an IP network. The practice of dividing a network into two or more networks is called subnetting. (or)
A subnet, or subnetwork, is a network inside a network. Subnets make networks more efficient. Through subnetting, network traffic can travel a shorter distance without passing through unnecessary routers to reach its destination.

The difference between public and private subnets:
- The instances in the public subnet can send outbound traffic directly to the Internet with the help of an Internet Gateway, whereas the instances in the private subnet cannot because we are not attaching an Internet Gateway to the Private Subnets.

== What do you mean by Root Device Name in Storage?

A bootable block device of the EC2 instance is called a root device. Each instance that you launch has an associated root device volume, which is either an Amazon EBS volume

= AWS EC2 Concepts and Features

== Spot Instance

A Spot Instance is an instance that uses spare EC2 capacity that is available for less than the On-Demand price. Because Spot Instances enable you to request unused EC2 instances at steep discounts, you can lower your Amazon EC2 costs significantly. The hourly price for a Spot Instance is called a Spot price. You can use Spot Instances for applications and workloads that require a fast network, quick storage, massive amounts of memory, and high computing capabilities.

== Reserved Instance

An Amazon Reserved Instance (RI) is a billing discount that allows you to save on your Amazon EC2 usage costs. When you purchase a Reserved Instance, you can set attributes such as instance type, platform, tenancy, Region, or Availability Zone (optional). Networking type of their Standard Reserved Instances and can be purchased for a 1-year or 3-year term.

== HVM vs PV Virtualization

The main differences between PV and HVM AMIs are the way in which they boot and whether they can take advantage of special hardware extensions (CPU, network, and storage) for better performance.

=== HVM AMIs

HVM AMIs are presented with a fully virtualized set of hardware and boot by executing the master boot record of the root block device of your image. This virtualization type provides the ability to run an operating system directly on top of a virtual machine without any modification, as if it were run on the bare-metal hardware. The Amazon EC2 host system emulates some or all of the underlying hardware that is presented to the guest. Unlike PV guests, HVM guests can take advantage of hardware extensions that provide fast access to the underlying hardware on the host system. HVM AMIs are required to take advantage of enhanced networking and GPU processing.

=== PV AMIs

PV AMIs boot with a special boot loader called PV-GRUB, which starts the boot cycle and then chain loads the kernel specified in the `menu.lst` file on your image. Paravirtual guests can run on host hardware that does not have explicit support for virtualization, but they cannot take advantage of special hardware extensions such as enhanced networking or GPU processing. Historically, PV guests had better performance than HVM guests in many cases, but because of enhancements in HVM virtualization and the availability of PV drivers for HVM AMIs, this is no longer true.

== Sharing Custom AMI to Different AWS Accounts

Yes, you can share an AMI with specific AWS accounts without making the AMI public. All you need is the AWS account IDs.

1. Choose AMIs.
2. Actions → Edit AMI permissions.
3. Choose Private.
4. Under Shared accounts, choose Add account ID.
5. Enter the AWS account ID with which you want to share the AMI, and then choose Share AMI.
6. Save changes.

== Copying Custom AMI to Different Regions

Yes, you can copy an Amazon Machine Image (AMI) into or to another AWS Region using the AWS Management Console, the AWS Command Line Interface, or SDKs, or the Amazon EC2 API.

1. Choose AMIs.
2. Actions → Copy AMI.
3. AMI copy name.
4. Choose your Destination Region.
5. Copy tags (optional) & Encrypt EBS snapshots of AMI copy (optional).
6. Copy AMI.

== Volume Types

* General Purpose SSD volumes.
** Volume type - gp2 and gp3
** Volume size: 1 GiB - 16 TiB
** Max IOPS per volume (16 KiB I/O): 16,000
** Max throughput per volume: 1,000 MiB/s (gp3), 250 MiB/s (gp2)
** Amazon EBS Multi-attach: Not supported
** Boot volume: Supported

* Provisioned IOPS SSD volumes
** Volume type - io2 Block Express | io2 | io1
** Volume size: 4 GiB - 64 TiB (io2 Block Express), 4 GiB - 16 TiB (io2, io1)
** Max IOPS per volume (16 KiB I/O): 256,000 (io2 Block Express), 64,000 (io2, io1)
** Max throughput per volume: 4,000 MiB/s (io2 Block Express), 1,000 MiB/s (io2, io1)
** Amazon EBS Multi-attach: Supported
** Boot volume: Supported

* Throughput Optimized HDD and Cold HDD volumes.
** Volume type - st1 (Throughput Optimized HDD) | sc1 (Cold HDD)
** Volume size: 125 GiB - 16 TiB
** Max IOPS per volume (1 MiB I/O): 500 (st1), 250 (sc1)
** Max throughput per volume: 500 MiB/s (st1), 250 MiB/s (sc1)

* Previous generation Magnetic volumes.
** Volume type - standard
** Use cases: Workloads where data is infrequently accessed
** Volume size: 1 GiB - 1 TiB
** Max IOPS per volume: 40–200
** Max throughput per volume: 40–90 MiB/s
** Boot volume: Supported

== Modifying a Volume

Yes, you can modify your volume.

1. Choose Volumes.
2. Select the volume to modify and choose Actions → Modify volume.
3. The Modify volume screen displays the volume ID and the volume's current configuration, including type, size (increase), IOPS, and throughput.
4. After modifying a volume, you must wait at least six hours and ensure that the volume is in the in-use or available state before you can modify the same volume again.

== Copying a Snapshot from One Region to Another Region

1. Go to the volume where your EBS snapshot resides.
2. Select the EBS snapshot you want to copy to another region and then click on the Copy Snapshot button.
3. Put a name and description on the EBS snapshot you want to copy to another region and then select the region you want to copy it to.

== Creating an AMI/Image from a Snapshot

1. Under Elastic Block Store, choose Snapshots.
2. Choose the snapshot and choose Actions → Create Image.
3. In the Create Image from EBS Snapshot dialog box, complete the fields to create your AMI, then choose Create.

== Nested Security Groups

The process of putting one group inside another group. Nested groups inherit the permissions and privileges of the group they are put under, making privilege administration easier.

== Placement Groups

A cluster placement group is a logical grouping of instances within a single Availability Zone that benefit from low network latency, high network throughput. A spread placement group places instances on distinct hardware. You can use placement groups to influence the placement of a group of interdependent instances to meet the needs of your workload.

* Cluster Placement Group: A directive to launch EC2 instances within the same rack in the same AZ.
* Partition Placement Group: Distributes instances across logical partitions.
* Spread Placement Group: Places instances on distinct hardware.

== Internal Application Load Balancer

1. Under Load Balancing, choose Load Balancers.
2. Choose Create Load Balancer.
3. Under Application Load Balancer, choose Create.

== Listener

A listener is a process that checks for connection requests, using the protocol and port that you configure. The rules that you define for a listener determine how the load balancer routes requests to its registered targets.

== Listener Protocols in Application Load Balancer

Application Load Balancers provide native support for HTTP/2 with HTTPS listeners. You can send up to 128 requests in parallel using one HTTP/2 connection. You can use the protocol version to send the request to the targets using HTTP/2.

== Target Types in Application Load Balancer Target Groups

* Instances
** Supports load balancing to instances within a specific VPC.
** Facilitates the use of Amazon EC2 Auto Scaling to manage and scale your EC2 capacity.

* IP addresses
** Supports load balancing to VPC and on-premises resources.
** Facilitates routing to multiple IP addresses and network interfaces on the same instance.
** Offers flexibility with microservice-based architectures, simplifying inter-application communication.
** Supports IPv6 targets, enabling end-to-end IPv6 communication, and IPv4-to-IPv6 NAT.

* Lambda function
** Facilitates routing to a single Lambda function.
** Accessible to Application Load Balancers only.

* Application Load Balancer
** Offers the flexibility for a Network Load Balancer to accept and route TCP requests within a specific VPC.
** Facilitates using static IP addresses and PrivateLink with an Application Load Balancer.

When you create a target group, you specify its target type, which determines the type of target you specify when registering targets with this target group. After you create a target group, you cannot change its target type.

== Target Group Protocols in Application Load Balancer

* TCP → 80
* HTTP → 80
* HTTPS → 443
* TLS → 443
* UDP → 53
* TCP_UDP → 53
* GENEVE → 6081

.Health Check Protocols in Target Group
[options="header"]
|===
| Parameter | Description | Default Value | Range

| Health Check Protocol
| The protocol the load balancer uses when performing health checks on targets. The possible protocols are HTTP and HTTPS.
| HTTP
| HTTP, HTTPS

| Health Check Port
| The port the load balancer uses when performing health checks on targets.
| The port on which each target receives traffic from the load balancer
| -

| Health Check Path
| The destination for health checks on the targets. If the protocol version is HTTP/1.1 or HTTP/2, specify a valid URI (/path?query). The default is /. If the protocol version is gRPC, specify the path of a custom health check method with the format /package.service/method.
| / (HTTP/1.1 or HTTP/2), /AWS.ALB/health check (gRPC)
| -

| Health Check Timeout Seconds
| The amount of time, in seconds, during which no response from a target means a failed health check.
| 5 seconds (instance or ip), 30 seconds (lambda)
| 2-120 seconds

| Health Check Interval Seconds
| The approximate amount of time, in seconds, between health checks of an individual target.
| 30 seconds (instance or ip), 35 seconds (lambda)
| 5-300 seconds

| Healthy Threshold Count
| The number of consecutive successful health checks required before considering an unhealthy target healthy.
| 5
| 2-10

| Unhealthy Threshold Count
| The number of consecutive failed health checks required before considering a target unhealthy.
| 2
| 2-10
|===


== Difference between SSL/TLS/TCP/UDP/HTTP/HTTPS/SSH/FTP/PING/ICMP

. SSL
Secure sockets layer (SSL) is a networking protocol designed for securing connections between web clients and web servers over an insecure network.

. TLS
TLS is a cryptographic protocol that provides end-to-end security of data sent between applications over the Internet.

. TCP
Transmission Control Protocol (TCP) is a standard that defines how to establish and maintain a network conversation by which applications can exchange data.

. UDP
User Datagram Protocol (UDP) operates on top of the Internet Protocol (IP) to transmit datagrams over a network. UDP does not require the source and destination to establish a three-way handshake before transmission takes place. Additionally, there is no need for an end-to-end connection.

. HTTP
HyperText Transfer Protocol (HTTP) is the communications protocol used to connect to Web servers on the Internet or on a local network (intranet). The primary function of HTTP is to establish a connection with the server and send HTML pages back to the user's browser. It is also used to download data from the server either to the browser or to any requesting application that uses HTTP.

. HTTPS
HTTPS stands for Hypertext Transfer Protocol Secure. It is the protocol where encrypted HTTP data is transferred over a secure connection. By using secure connections such as Transport Layer Security or Secure Sockets Layer, the privacy and integrity of data are maintained and authentication of websites is also validated.

. SSH
SSH stands for Secure Shell or Secure Socket Shell. It is a cryptographic network protocol that allows two computers to communicate and share data over an insecure network such as the Internet. It is used to login to a remote server to execute commands and data transfer from one machine to another machine. The SSH protocol was developed by SSH communication security Ltd to safely communicate with the remote machine.

. FTP
File Transfer Protocol (FTP) is the most common way of sending and receiving files between two computers. File Transfer Protocol (FTP) is a client/server protocol used for transferring files to or from a host computer. FTP may be authenticated with usernames and passwords.

. PING
A ping (Packet Internet or Inter-Network Groper) is a basic Internet program that allows a user to test and verify if a particular destination IP address exists and can accept requests in computer network administration.

. ICMP
Internet Control Message Protocol (ICMP) is a network-level protocol. ICMP messages communicate information about network connectivity issues back to the source of the compromised transmission. It sends control messages such as destination network unreachable, source route failed, and source quench.

== Healthy Threshold / Unhealthy Threshold / Timeout / Interval

. Healthy Threshold
The number of consecutive successful health checks that must occur before declaring an EC2 instance healthy. Valid values: 2 to 10. Default: 10.

. Unhealthy Threshold
The number of consecutive failed health checks that must occur before declaring an EC2 instance unhealthy. Valid values: 2 to 10. Default: 2.

. Timeout / Response timeout
The amount of time to wait when receiving a response from the health check, in seconds. Valid values: 2 to 60. Default: 5.

. Interval
The amount of time between health checks of an individual instance, in seconds. Valid values: 5 to 300. Default: 30.

. Protocol
The protocol to use to connect with the instance. Valid values: TCP, HTTP, HTTPS, and SSL. Console default: HTTP, CLI/API default: TCP.

. Path
The port to use to connect with the instance, as a protocol:port pair. If the load balancer fails to connect with the instance at the specified port within the configured response timeout period, the instance is considered unhealthy.

== Available Target Group Protocols in Network Load Balancer Target Group

. TCP
80

. TLS
443

. UDP
53

. TCP_UDP
53

== Listener Rule Conditions

. Listener
A listener is a process that checks for connection requests, using the protocol and port that you configure. The rules that you define for a listener determine how the load balancer routes requests to its registered targets.

. Listener rule
The rules that you define for your listener determine how the load balancer routes requests to the targets in one or more target groups. Each rule must include exactly one of the following actions: forward, redirect, or fixed-response, and it must be the last action to be performed. Each rule can include zero or one of the following conditions: host-header, http-request-method, path-pattern, and source-ip, and zero or more of the following conditions: http-header and query-string. You can specify up to three comparison strings per condition and up to five per rule.

== Launch Configurations

A launch configuration is an instance configuration template that an Auto Scaling group uses to launch EC2 instances. When you create a launch configuration, you specify information for the instances. Include the ID of the Amazon Machine Image (AMI), the instance type, a key pair, one or more security groups, and a block device mapping. If you've launched an EC2 instance before, you specified the same information in order to launch the instance.

You can specify your launch configuration with multiple Auto Scaling groups. However, you can only specify one launch configuration for an Auto Scaling group at a time, and you can't modify a launch configuration after you've created it. To change the launch configuration for an Auto Scaling group, you must create a launch configuration and then update your Auto Scaling group with it.

Keep in mind that whenever you create an Auto Scaling group, you must specify a launch configuration, a launch template, or an EC2 instance. When you create an Auto Scaling group using an EC2 instance, Amazon EC2 Auto Scaling automatically creates a launch configuration for you and associates it with the Auto Scaling group.

== Auto Scaling Groups

An Auto Scaling group contains a collection of EC2 instances that are treated as a logical grouping for the purposes of automatic scaling and management. An Auto Scaling group also lets you use Amazon EC2 Auto Scaling features such as health check replacements and scaling policies. Both maintaining the number of instances in an Auto Scaling group and automatic scaling are the core functionality of the Amazon EC2 Auto Scaling service.

The size of an Auto Scaling group depends on the number of instances that you set as the desired capacity. You can adjust its size to meet demand, either manually or by using automatic scaling.

== Desired, Minimum, and Maximum Capacity in Auto Scaling Group

. Desired capacity
Represents the initial capacity of the Auto Scaling group at the time of creation. An Auto Scaling group attempts to maintain the desired capacity. It starts by launching the number of instances that are specified for the desired capacity, and maintains this number of instances as long as there are no scaling policies or scheduled actions attached to the Auto Scaling group.

. Minimum capacity
Represents the minimum group size. When scaling policies are set, an Auto Scaling group cannot decrease its desired capacity lower than the minimum size limit.

. Maximum capacity
Represents the maximum group size. When scaling policies are set, an Auto Scaling group cannot increase its desired capacity higher than the maximum size limit.

== Differences between Step Scaling Policies and Simple Scaling Policies

Step scaling policies and simple scaling policies are two of the dynamic scaling options available for you to use. Both require you to create CloudWatch alarms for the scaling policies. Both require you to specify the high and low thresholds for the alarms. Both require you to define whether to add or remove instances, and how many, or set the group to an exact size.

The main difference between the policy types is the step adjustments that you get with step scaling policies. When step adjustments are applied, and they increase or decrease the current capacity of your Auto Scaling group, the adjustments vary based on the size of the alarm breach.

== Scaling Policies in Auto Scaling Group

AWS Auto Scaling monitors your applications and automatically adjusts capacity to maintain steady, predictable performance at the lowest possible cost. Using AWS Auto Scaling, it's easy to set up application scaling for multiple resources across multiple services in minutes.

Step scaling policies increase or decrease the current capacity of a scalable target based on a set of scaling adjustments, known as step adjustments. The adjustments vary based on the size of the alarm breach. All alarms that are breached are evaluated by Application Auto Scaling as it receives the alarm messages.

The three components of EC2 Auto Scaling are scaling policies, scaling activities, and scaling processes.

== Target Tracking Scaling Policy

A target tracking scaling policy prioritizes availability during periods of fluctuating traffic levels by scaling in more gradually when traffic is decreasing. If you want your Auto Scaling group to scale in immediately when a workload finishes, you can disable the scale-in portion of the policy.

== Metric Types Available in Target Tracking Scaling Policy

. ASGAverageCPUUtilization
Average CPU utilization of the Auto Scaling group.

. ASGAverageNetworkIn
Average number of bytes received by a single instance on all network interfaces.

. ASGAverageNetworkOut
Average number of bytes sent out from a single instance on all network interfaces.

. ALBRequestCountPerTarget
Average Application Load Balancer request count per target.

== Adding Notifications in Auto Scaling Groups

AWS Auto Scaling is a way to manage a dynamic fleet of EC2 instances. The Auto Scaling Group will keep the number of running instances in sync with the desired value while the desired value stays in a boundary defined by min and max instances. AWS Auto Scaling Notifications are triggered on:

- Successful instance launch
- Failed instance launch
- Successful instance termination
- Failed instance termination

Steps to add notifications:

1. Click on the Auto Scaling Groups link on the left.
2. Select the Auto Scaling Group you want to monitor.
3. Select the Notifications tab.
4. Click on the Create notification button.
5. Set Send a notification to the mail SNS topic.
6. In Whenever instances, select the events you are interested in.
7. Save by clicking the Save button.

== Dynamic Scaling Policy in Auto Scaling Group

The dynamic scaling capabilities of Amazon EC2 Auto Scaling refer to the functionality that automatically increases or decreases capacity based on load or other metrics. For example, if your CPU spikes above 80% (and you have an alarm set up), Amazon EC2 Auto Scaling can add a new instance dynamically.

Dynamic scaling scales the capacity of your Auto Scaling group as traffic changes occur:
. Dynamic Horizontal Scaling
IT resource instances are scaled out and in to handle fluctuating workloads.
. Dynamic Vertical Scaling
IT resource instances are scaled up and down when there is a need to adjust the processing capacity of a single IT resource.

== Policy Types in Dynamic Scaling Policy

. Dynamic Horizontal Scaling
IT resource instances are scaled out and in to handle fluctuating workloads.
. Dynamic Vertical Scaling
IT resource instances are scaled up and down when there is a need to adjust the processing capacity of a single IT resource.

. Target tracking scaling
Increase and decrease the current capacity of the group based on an Amazon CloudWatch metric and a target value. It works similar to the way that your thermostat maintains the temperature of your home—you select a temperature and the thermostat does the rest.

. Step scaling
Increase and decrease the current capacity of the group based on a set of scaling adjustments, known as step adjustments, that vary based on the size of the alarm breach.

. Simple scaling
Increase and decrease the current capacity of the group based on a single scaling adjustment, with a cooldown period between each scaling activity.
