= IP Address Classes and Related Information

== IP Address Classes
:author: Manu V
:date: 2024-07-04
:revnumber: 1.0
:revdate: 2024-07-04
:doctype: article


An IP (Internet Protocol) address is a unique identifier assigned to each device connected to a network. It enables devices to communicate with each other over an IP-based network like the internet.

== Types of IP Addresses

There are two main types of IP addresses:

1. IPv4
2. IPv6

=== IPv4

IPv4 (Internet Protocol version 4) is the fourth version of the Internet Protocol. It uses a 32-bit address scheme allowing for a total of 2^32 addresses (approximately 4.3 billion addresses).

[example]
====
IPv4 Address Example: `192.168.1.1`
====

==== IPv4 Address Classes

IPv4 addresses are divided into five classes:

- Class A: `1.0.0.0` to `126.255.255.255`
- Class B: `128.0.0.0` to `191.255.255.255`
- Class C: `192.0.0.0` to `223.255.255.255`
- Class D (Multicast): `224.0.0.0` to `239.255.255.255`
- Class E (Experimental): `240.0.0.0` to `255.255.255.255`

=== IPv6

IPv6 (Internet Protocol version 6) is the most recent version of the Internet Protocol. It uses a 128-bit address scheme allowing for a total of 2^128 addresses, which provides a vastly larger address space compared to IPv4.

[example]
====
IPv6 Address Example: `2001:0db8:85a3:0000:0000:8a2e:0370:7334`
====

== Public vs Private IP Addresses

IP addresses can be categorized as either public or private.

=== Public IP Addresses

Public IP addresses are assigned to devices that are directly connected to the internet. These addresses are globally unique and are managed by the Internet Assigned Numbers Authority (IANA).

=== Private IP Addresses

Private IP addresses are used within a private network and are not routable on the internet. They are reserved for use in local networks.

.Private IPv4 Address Ranges
[cols="2,3"]
|===
| Class | Range
| Class A | `10.0.0.0` to `10.255.255.255`
| Class B | `172.16.0.0` to `172.31.255.255`
| Class C | `192.168.0.0` to `192.168.255.255`
|===
// == Private Address Space
//
// * 10.0.0.0 to 10.255.255.255
//
// * 172.16.0.0 to 172.31.255.255
//
// * 192.168.0.0 to 192.168.255.255


== Subnetting

Subnetting is a method used to divide a single IP network into multiple smaller networks. It improves network performance and management.

=== Subnet Mask

A subnet mask is used to divide an IP address into a network and host portion. It helps determine which part of an IP address is the network address and which part is the host address.

[example]
====
IP Address: `192.168.1.1`
Subnet Mask: `255.255.255.0`
====

In this example, the subnet mask `255.255.255.0` indicates that the first three octets (`192.168.1`) represent the network portion, and the last octet (`1`) represents the host portion.

=== CIDR Notation

Classless Inter-Domain Routing (CIDR) is a method for allocating IP addresses and routing. CIDR notation specifies an IP address and its associated routing prefix.

[example]
====
CIDR Notation: `192.168.1.1/24`
====

In this example, `/24` indicates that the first 24 bits are the network portion of the address, leaving the remaining 8 bits for host addresses.

=== Subnetting Calculation

To create subnets, you need to understand how to calculate the number of subnets and hosts per subnet.

[cols="2,3"]
|===
| Formula | Description
| Number of Subnets | `2^n` (where `n` is the number of bits borrowed for subnetting)
| Number of Hosts per Subnet | `2^(32-n) - 2` (where `n` is the number of bits for the subnet mask)
|===

[example]
====
For a `/26` subnet mask:

- Subnet Mask: `255.255.255.192`
- Number of Subnets: `2^(26-24) = 2^2 = 4`
- Number of Hosts per Subnet: `2^(32-26) - 2 = 2^6 - 2 = 64 - 2 = 62`
====

=== Benefits of Subnetting

- Improved network performance
- Enhanced security
- Efficient IP address management
- Reduced network congestion

=== Default Subnet Masks

* Class A: 255.0.0.0

* Class B: 255.255.0.0

* Class C: 255.255.255.0


== Network Addresses
Using the IP address and subnet mask shown write out the network address:

|===
| IP Address         | Subnet Mask      | Network Address

| 188.10.18.2        | 255.255.0.0      | 188 . 10 . 0 . 0

| 10.10.48.80        | 255.255.255.0    | 10 . 10 . 48 . 0

| 192.149.24.191     | 255.255.255.0    | 192 . 149 . 24 . 0

| 150.203.23.19      | 255.255.0.0      | 150 . 203 . 0 . 0

| 10.10.10.10        | 255.0.0.0        | 10 . 0 . 0 . 0

| 186.13.23.110      | 255.255.255.0    | 186 . 13 . 23 . 0

| 223.69.230.250     | 255.255.0.0      | 223 . 69 . 0 . 0

| 200.120.135.15     | 255.255.255.0    | 200 . 120 . 135 . 0

| 27.125.200.151     | 255.0.0.0        | 27 . 0 . 0 . 0

| 199.20.150.35      | 255.255.255.0    | 199 . 20 . 150 . 0

| 191.55.165.135     | 255.255.255.0    | 191 . 55 . 165 . 0

| 28.212.250.254     | 255.255.0.0      | 28 . 212 . 0 . 0
|===

== Host Addresses
Using the IP address and subnet mask shown write out the host address:


|===
| IP Address         | Subnet Mask      | Host Address

| 188.10.18.2        | 255.255.0.0      | 0 . 0 . 18 . 2

| 10.10.48.80        | 255.255.255.0    | 0 . 0 . 0 . 80

| 222.49.49.11       | 255.255.255.0    | 0 . 0 . 0 . 11

| 128.23.230.19      | 255.255.0.0      | 0 . 0 . 230 . 19

| 10.10.10.10        | 255.0.0.0        | 0 . 10 . 10 . 10

| 200.113.123.11     | 255.255.255.0    | 0 . 0 . 0 . 11

| 223.169.23.20      | 255.255.0.0      | 0 . 0 . 23 . 20

| 203.20.35.215      | 255.255.255.0    | 0 . 0 . 0 . 215

| 117.15.2.51        | 255.0.0.0        | 0 . 15 . 2 . 51

| 199.120.15.135     | 255.255.255.0    | 0 . 0 . 0 . 135

| 191.55.165.135     | 255.255.255.0    | 0 . 0 . 0 . 135

| 48.21.25.54        | 255.255.0.0      | 0 . 0 . 25 . 54
|===

== Default Subnet Masks
Write the correct default subnet mask for each of the following addresses:


== References

- https://www.iana.org/
- https://www.ietf.org/
