== Python

Python was designed and developed by **Guido Van Rossum**. +
The name comes from the Monty Python's Circus show on the BBC. +
Official website: http://www.python.org +

Python is a programming language used to write the coding part for application development.

== Django

Django is a web application development framework used to design and develop websites.

== Python Features

Python is a general-purpose, high-level, interpreted, dynamically typed, and case-sensitive programming language.

- *High level*: No need to manage memory and security-related aspects; these are handled by default.
- *Interpreted*: Python and JavaScript are interpreted languages, meaning they check and execute code line by line. They are also **dynamically typed**.

Example of dynamically typed:

ex:

    datatype varibalename=value
    a=10

- *Compiler-based*: Group of lines (the whole program code) are checked once and executed. These are **statically typed** languages. Examples include Java, C, C++, C#, and .NET.

Example of statically typed:

ex:

 datatype variablename = value;
 int x = 10;

why python?

huge standard libraries

NOTE: **immutable** : cannot change and **mutable** : can change



== Application area of python:

1. Standalone or desktop app -  console App(CUI) and Desktop GUI
2. web application(Django framework or flask)
3. Databased application
4. Gaming application
5. Data analysis (Datascience)
6. Statistical analysis
7. Testing, AI, ML, Devops, IOT, Business app, Network programming.

== Features of Python

. Simple and easy to learn
. Free and Open Source
. High Level
. Platform Independent (cross-platform)
. Portability ( one platform(windows) to other(linux) platform shift easy)
. Dynamically typed
. Procedure and object-oriented
. Extensible and Extensive library


== Different ways t write python script and execute:

1. Using Interactive mode
2. Using script mode(.py)
3. Using python IDLE
4. Using Pycharm editor


== Fundamental Concepts

===  1. Comments in python

- Single line comment

ex:
[source,python]
----
#this is single line comment
This is un-comment line
----

- Multi line comment

ex:
[source,python]
----
'''
this is multi line
comment example
'''
this is un-comment line
----

=== 2. Keywords and reserved words

keyword is library and this keyword are reserved form python, keywords cant be used as variable or personal use case.

ex:
[source,python]
----
import keyword
print(keyword.kwlist)
----

Output:

  ['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


=== 3. Indentation


4 spaces

=== 4. Identifiers

- Rule to define Identifier
. lowercase or Uppercase (ex:01)
. case sensitive
. allow digits(0-9) it should not Start with digits (ex:02)
. should not be two parts (ex:03)
. allow underscore(_)
. if an identifier starts with underscore then it is private
. we cant use any keyword or reserved word as identifier (ex:04)


ex:01
[source,python]
----
empid = 1234
   print(EMPID) # This is wrong it should be match with variable
   print(empid) # This is correct
----
NOTE: Always use lowercase for best pratices

ex:02
[source,python]
----
empid01 = 1234
01empid = 1234
   print(empid01) # This is correct
   print(01empid)  # This is wrong it should not start with digits
----

(ex:03)
[source,python]
----
emp id = 1234
empid = 1234
   print(emp id) # This is wrong it should not be two parts
   print(empid) # This is correct
----

(ex:04)
[source,python]
----
def = 1234
deff = 1234
   print(deff) # This is correct
   print(def) # This is wrong it should not keyword or reserved word as identifier
----


=== 5. Variables

. Variable is also consider as identifier
. variable is a named memory location
. while declaring the variable in python we need not specify any datatype because python is dynamically typed programming languages
. based on the value datatype will decide implicitly

(ex:01)
[source,python]
----
a = 1234
b = 10.9
c = "s"
   print(a)
   print(type(a)
   print(b)
   print(type(b)
   print(c)
   print(type(c)
----

==== 6. Multiple assignment
. Is the process of assigning the multiple value to multiple variables (ex:01)
. Is the process of assigning a single value to multiple variables (ex:02)


ex:01
[source,python]
----
a,b,c=10,20,30
    print(a,end=",")
    print(b,end=",")
    print(c) # here there is value for c attribute so we cant use end attribute for `c` value

----

ex:02
[source,python]
----
a = b = c = 10
   print(a,b,c) #or
   print(a)
   print(b)
   print(c)
   print(a,b,c,sep=":")
----


== DataTypes

Datatype is used to represent what type of values are going to store inside the variable.

=== Basic Datatype
// . None
// . Numeric
// - int
// - float
// - bool
// - complex
//
// . Sequence Datatype:
//
// -  String
// -  list
// - tuple
// - set
// - dict
// - range
// - bytes
// - bytearray
// - fronzenset

|===
| Basic Datatype | Description

| None
| Represents the absence of a value

| Numeric
| Represents numeric values

| int
| Integer numbers (e.g., -1, 0, 42)

| float (ex:02)
| Floating-point numbers (e.g., 3.14, -0.001)

| bool
| Boolean values (True or False)

| complex
| Complex numbers with a real and imaginary part

| Sequence Datatype
| Description

| String
| Ordered collection of characters (immutable)

| list
| Ordered collection of items (mutable)

| tuple
| Ordered collection of items (immutable)

| set
| Unordered collection of unique items

| dict
| Collection of key-value pairs

| range
| Sequence of numbers commonly used for looping

| bytes
| Sequence of integers representing raw binary data (immutable)

| bytearray
| Mutable sequence of integers representing binary data

| frozen set
| Immutable set of unique items

|===



ex:
[source,python]
----
a = None #in python
b = null #in other langauges
  print(a)
  print(b)
  print(type(a))
  print(type(b)) # you will get error and difference for python and other langauges
----


ex:
[source,python]
----
c = 10 # int
d = 5.5  # float
  print(c)
  print(d)
  print(type(c))
  print(type(d))

# how to convert int to float

e = float(c)
 print(e)
 print(type(e)) # converted `int to float`

 # how to convert   float to int

f = int(d)
 print(f)
 print(type(f)) # converted ` float to int`
----

ex:
[source,python]
----
name = " raju "
  print("your name is:",name)   #
name = input("Enter your Name:")  # run time inputs
  print("your name is:",name)
  print(type(name))
----


ex:
[source,python]
----
a = input("Enter A number:") # by default it will take as string so you need change to int
 print(type(a))
x = int(a)
 print(type(a))
b = input("Enter B number:") # by default it will take as string so you need change
 print(type(b))
y = int(b)
 print(type(y))
c = a+b
z = x+b
print(The result is:",c)
print(The result is:",z)
#output
#1020

----
NOTE: All inputs are taken as strings by default; explicit conversion is required for other data types. Conversion mechanism only for runtime execution

ex:
[source,python]
----
a = input(Enter Num1:")
b = input(Enter Num2:")
 print("result is:",a+b)

x = float(input(Enter Num1:"))
y = float(input(Enter Num2:"))
 print("result is:",x+y)
----

====  bool Datatype

only allowed value True as 1 and False as 0

ex: 01
[source,python]
----
a = 10
b = 20
c=a<b  #True
d=a>b  #False
 print(C)
 print(d)
 print(type(c))
 print(type(d))
 print(True+True)
 print(True+9)
----

==== complex
a+bj # j is imagernay numbers
ex:01
[source,python]
----
a=2
b=3
c=complex(a,b)
 print(c)
 print(type(c))
 print(c.real) # To print real and imagenary values
 print(c.imag)  # To print real and imagenary values 
----

ex:02
[source,python]
----
a=2+3j
b=5+2j
 print(a+b)
----


==== Sequence Datatype

**String**   :  String is a sequence of characters or group od character string can be represented with string and string can be created by using '' or "" or '''  ''' or """ """




print(dir(list))


help(str) #any str like list, tuple

=== Properties of Python Data Structures


[cols="1,1,1,1,1,1"]
|===
| DS      | create   | ordered | mutable    | immutable | duplicate

| str     | '' or "" | yes     | no         | yes       | yes
| list    | [ ]       | yes     | yes        | no        | yes
| tuple   | ( )       | yes     | no         | yes       | yes
| set     | { }       | no      | yes        | no        | no
| dict    | { }       | no      | keys: no  values: yes  | keys: yes values: no| keys: no values: yes
| range   | range()  | yes     | no        | yes       | no
|===



**list** :

. List is ordered collection of elements
. list can be created by using` [ ]`
. List will allow duplicate elements
. List contains different datatype elements
. List is mutable, once we create wa list that can change

ex:01
[source,python]
----
l = [10,20,30,"a",20,50]
  print(l)
  print(type(l))
----
**tuple** :

. tuple is ordered collection of elements
. tuple can be created by using `( )` but brackets are optional
. tuple will allow duplicate elements
. tuple contains different datatype elements
. tuple is immutable, once we create a tuple that cannot be change

NOTE: To create tuple with single element, after element we should give comma(,)

ex:01
[source,python]
----
t = (10,) #here for single element
  print(t)
  print(type(t))

----


ex:02
[source,python]
----
t = (10.0, 10, 20, "xyz", 'a', 23)
  print(t)
  print(type(t))
----


set :

. set is unordered collection of unique element.
. set can be created by using `{ }`.
. set contains different datatype elements.
. set is mutable once we create a set that can be modified.
. set will not allow duplicate values.
. To create an empty set then we use set() function.

NOTE:

ex:01
[source,python]
----
s = set()
q = {10, "sai", 'a', 20.3, 10,'a'} # no duplicate allowed, un-orderd(indexing is not fallowed).
  print(s)
  print(q)
  print(type(s))
  print(type(q))
----

**dect** :

. dect is unorderd collection of items.
. dict can be created by using { }.
. In dict each item can be a pair i.e key and value.
. keys are immutable, we cant change and values are mutable, we can change the values.
. In dict keys and value can be any type
. In dict keys must be unique and value need not be unique.

ex:01
[source,python]
----
d = {}
d1 = {1:"sai", name:"xyz", 3:"23.43"}
 print(type(d))
 print(type(d1))

----

**range** :

. range is ordered collection of values.
. range is used to generate sequence of values.
. range is immutable, once we create a range that cant change by default range will start from Zero
. To create range of values then we use range function.

ex:01
[source,python]
----
r = range(10)
a = range(2,11,2) #start stop step
  print(d)
  print(type(r))
  print(list(r)) #to print all sequence of value
  print(list(a)) # here we cna use tuple or any datatype
----
== Operators in python

Operater is symbole which is used to perform required operations. Python supports tha fallowing operators

1. Arithmetic
2. Relational
3. Assignment
4. Logical
5. Membership
6. Identity
7. Bitwise

=== Arithmentic:

==== Python Arithmetic Operators

[cols="1,1"]
|===
| Symbol  | Operation

| +       | addition
| -       | subtraction
| *       | multiplication
| **      | exponentiation(Power)
| /       | division
| //      | floor division
| %       | modulus
|===

ex:01
[source,python]
----
a = 10
b = 5
print(a+b) #addition
print(a-b) #subtraction
print(a*b) #multiplication
print(a**b) #exponentiation(Power)
print(a/b) #division
print(a//b) #floor division
print(a%b) #modulus
----

=== Relational:

=== Python Comparison Operators

[cols="1,1"]
|===
| Symbol  | Operation

| <       | less than
| >       | greater than
| < =      | less than or equal to
| >=      | greater than or equal to
| ==      | equal to
| !=      | not equal to
|===

ex:01
[source,python]
----
print(3<2)
print(3>2)
print(3>=2)
print(3<=2)
print(3==2)
print(3!=2)
----

=== Assignment

=== Python Assignment Operators

[cols="1,1"]
|===
| Symbol  | Operation

| =       | assign
| +=      | add and assign
| -=      | subtract and assign
| *=      | multiply and assign
| /=      | divide and assign
| //=     | floor divide and assign
| %=      | modulus and assign
|===


ex:01
[source,python]
----
a = 5
 print(a)

a+=2
 print(a)

b-=2
 print(b)

c*=2
  print(c)

d/=2
 print(d)

a//=2
  print(a)

a%=2
  print(a)
----


=== Logical

=== Python Logical Operators

[cols="1,1"]
|===
| Symbol | Operation

| and    | returns true if both conditions are true, else false
| or     | returns true if any one of the conditions is true or both conditions are true, else false
| not    | returns true if the condition is false, returns false if the condition is true
|===

ex:01
[source,python]
----
print(3<2 and 4<5)
print(3>2 and 4<5)

print(3<2 or 4<5)
print(3>2 or 4<5)
print(3<2 or 4>5)

print(not 4<5)
print(not 4>5)


----


=== Membership :
Membership operator are used to check whether than value is present in given sequence or not

=== Python Membership Operators

[cols="1,1"]
|===
| Symbol   | Operation

| in       | returns true if the value is present in the given sequence, else false
| not in   | returns true if the value is not present in the given sequence, else false
|===



ex:01
[source,python]
----
l = [10,20,30,40,50]
 print(10 in l)
 print(70 in l)

 print(100 not in l)
 print(10 not in l)

 print( 'r' in "Ranga")
 print( 'x' in "Ranga")

----

=== Idenetity :
Idenetity operators are used to check whether tha varibales or any python objects are having same identity or not.

=== Python Identity Operators

[cols="1,1"]
|===
| Symbol | Operation

| is     | returns true if the variables have the same identity, else false
| is not | returns true if the variables do not have the same identity, else false
|===


NOTE: id() : it is a builtin function in python, ir is used to find memory address of the object and it will return always unique interger.

ex:01
[source,python]
----
a = 2
b = 2
c = 4
d = 5
 print(a is b)
 print(a is not b)
 print(c is d)
 print( c is not d)
----


ex:01
[source,python]
----
a = "sai"
b = "sai"

 print(id(a)) # here memory address will be same a & b
 print(id(b))
----

=== Bitwise operators:
1. bitwise AND(&)
2. bitwise OR(|)
3. bitwise XOR(^)
4. bitwise NOR(~)
5. leftshift (<<)
6. rightshift (<<)

// ex:01
// [source,python]
// ----
//
// ----


=== Control flow statements:
1. Conditional Statements (**if, if else,nested if,elif** )
2. Iterative Statements (**for, while** )
3. Transfer statements (**break,continue,pass** )


==== Conditional Statements:
. **if** : `if` is used to test specific condition, if the condition is ture `if` block will execute
. **if else**
[source,python]
----
if condition:
statement
----


ex:01
[source,python]
----
n = int(input("Enter a number:"))

if n%2==0:
  print(n, "is Even")
else
  print(n, "is Odd")

i = 10
if i == 100:
   print("true")
else:
   print("false")

----

. **nested if** : Is used to check multiple conditions using `if` and `else if`

ex:01
[source,python]
----
i = int(input("Enter a number:" )) #i : 17

if i>20:
  print(i, "Is garter than 20")
else:
  if i>15:
    print(i, "Is garter than 15")
  else:
    print(i, "Is not garter than 15 and 20")


----

. **elif** : elif us the short form of `else if`

ex:01
[source,python]
----
i = int(input("Enter a number:"))
#here it will check all conditation if you given correct number
if i == 1:
     print("one")
elif i == 2:
     print("two")
elif i == 3:
     print("three")
elif i == 4:
     print("four")
else:
     print("Invalid Number")
----

==== Iterative Statements
. **for**:
for loop is used to iterate tha element of collection whar tha order they apper

[source,python]
----
for varibalename in sequence:
    statements
----
ex:01
[source,python]
----
#    0   1  2  3  4
l = [10,20,30,40,50,"xyz",20.15,'a',75]

print(l[0])
print(l[0])# here we cant print one by one

for i in l:
  print(i)
  print(type(i))
----


. **Nested for loop**:
A for loop which is having one more for loop within is called nested for loop.

[source,python]
----
for variablename in sequence:
    statements
     for variablename in sequence:
        statements
----

ex:01
[source,python]
----
#          0   1  2  3  4
numlist = [10,20,30,40,50]
charlist = ['a', 'b', 'c', 'd']

for n in numlist:
    print(n)
    for e in charlist:
          print(e)

----



NOTE: for every iteration of outer loop, inner loops should finish it's all iterations then only outer loop will start with next interation


. **while** : unknown iteration, like till the condition match

[source,python]
----
while condition:
    statements
----

ex:01
[source,python]
----
i = 1
  while i<=10:
         print(i,end=" ") # end function is to print all value in same name.
         i+=1 #i=i+1
----
==== Transfer statements

===== **break**: break is used to stop the iteration based on condition.

ex:01
[source,python]
----
for i in range(10):
   if i==4;
       break
   print(i,end=" ")
----

===== **continue**: continue is used to skip the current iteration and continue with the next iteration

ex:01
[source,python]
----
for i in range(10):
   if i==4 or i==6:
       continue
   print(i,end=" ") #it will skip that 4th number
----

ex:01
[source,python]
----
i = 1
while i<=10:
   if i==4:
        i+=1
       continue
   print(i,end=" ")
   i+=1
----
===== **pass**

ex:01
[source,python]
----
i = 1
while i<=10:
      pass

for i in range(10):
    pass

a = 10
if i==10:
   print("ture")
else:
   print("false")
----



=== String Datastructures

----
print(dir(str))
----

1. How to create string

ex:01
[source,python]
----
name = "cloudcatalist"
  print(name)
  print(type(name)) #here we can use '' or "" or '''
----

ex:01
[source,python]
----

s = ''' hi this is
cloudcatalyst doc'''
 print(s)# multiple line string
----

ex:01
[source,python]
----
m = "cloudcatalyst's"
  print(m)
----

=== String indexing and string slicing
backward direction is not possible in string

ex:01
[source,python]
----
# 0     1    2     3    4     5     6     7     8     9    10    11    12
# c     l    o     u    d     c     a     t     a     l    y     s      t
# -13  -12  -11   -10  -9    -8    -7    -6    -5    -4   -3    -2     -1


s = "cloudcatalyst"
  print(s[0:5]) # output : cloud
  print(s[-7:0])
  print(s[:]) #it will take 0 to 12
  print(s[0:9:1]) #start stop step
  print(s[::-1]) # we can revers
  print()
----


=== string concatenation and string multiplication

ex:01
[source,python]
----
s1 = "cloud"
s2 = "catalyst"
  print(s1+" "+s2) # string concatenation
  print((s1+" ")*3) # to print multiple times (multiplication)
----
=== string split and max split

ex:01
[source,python]
----
s = "c l o u d c a t a l y s t"
  print(s)
s1=s.split(" ")
  print(s1)
  print(type(s1))
a= "python is very easy"

s2=a.split(",",4)
  print(s2)
  print(type(s2))
----

=== string capatlis

ex:01
[source,python]
----

a="python is very easy"

  print(a)
  print(a.capitalize)# it will return start latter as capitalize
or
s1=a.capitalize
  print(s1)


 print(s.title)# here very word as return as capitalize
----


=== string count

ex:01
[source,python]
----
s = "python is vary easy and it is oop and it is interperted"

substring="is"
 print(s.count(substring))# to know repeted char
 print(s.count(" "))# to know the space

----


=== string replace

ex:01
[source,python]
----
s = "python is vary easy and it is oop and it is interperted"

  print(s.replace("python","java")) # it will replace python to java
  print(s.replace(" ","*"))# it will replace space(_) to *

----

=== string upper and lower case

ex:01
[source,python]
----
s = "python is vary easy and it is oop and it is interperted"
 print(s)
 print(s.upper())
 print(s.lower())
----
=== string swap case

ex:01
[source,python]
----
s = "pyThon is vAry easy aNd It is PPp AND it Is interPErted"
 print(s)
 print(s.swapcase())

----

=== string revers

ex:01
[source,python]
----
s = "python"
 print(s)
 print(::-1)
----

ex:01
[source,python]
----
l = ["sai","ram","raj"]
 print(" ".join(resersed(l)))
 print(":".join(resersed("ramu")))
----

=== string sort

Directly we can't apply sort to string, need to convert into sort and print

ex:01
[source,python]
----
s = "python is very easy"
s1=s,split(" ")
s1.sort()
 print(s1)
s1.sort(reverse=Ture)
 print(s1)

----

=== string - strip()
It returns a copy of string with both leading and trailing character removed

ex:01
[source,python]
----
s = "   ramu   "

 print(s)#there is a space in rigth and left side

 print(s.strip(" "))

OR

a = "AramuA"

 print(s)#there is a "A" in rigth and left side

 print(s.strip("A"))



----


=== string - lstrip()
It returns a copy of the string with leading characture removed.

ex:01
[source,python]
----
h = "AramuA"

 print(h)#there is a "A" in rigth and left side

 print(h.ltrip("A"))

----


=== string - rstrip()
It returns a copy of the string with trailing charature removed.

ex:01
[source,python]
----
r = "AramuA"

 print(r)#there is a "A" in rigth and left side

 print(r.rtrip("A"))

----

=== string - length
It is used to find length of string


ex:01
[source,python]
----
r = "python is vary easy and it is oop and it is interperted"

  print(s)
  print(len(s)) # it will consider spaces also

----

=== string - Find and index and rindex
It is used to find substring from given string, and return -1 if there is no substring


index: index is used to find substring from given string , and it return error

ex:01
[source,python]
----
op = "python is vary easy and it is oop and it is interperted"

 print(op.find("is")) # it will fine first one (occourent)
 print(op.find("x"))# it will return -1 becouse there is no x on "op"

 print(op.index("is"))
 print(op.index("x"))# it will return error

 print(op.rindex("is")) # it will return highest index of given string
 print(op.rindex("x"))# it will return error

----

=== string - max( ) and min ( )

Max( ): Highest alphabetical character in string
min ( ): List alphabetical character in string

ex:01
[source,python]
----
a = "alphabetICAl"

 print(max(a))
  print(min(a))

  print(ord("a"))# It will return accsi value of character
  print(ord("A"))
----


=== string - partition( )
Split the string at the first occurrence of the separator and returns a tuple format.

ex:01
[source,python]
----
p = "python is vary easy and it is oop and it is interperted"
 print(p.partition("is"))
 print(type(p.partition("is")))

----

=== string - startswith( )

Startswith return Ture if a string starts with the given suffix otherwise returns False.


ex:01
[source,python]
----
s = "python"
 print(s.startswith("P")) #it will give you false becouse it cap case
 print(s.startswith("p")) #it's correct

----


=== string - endswith( )
Endswith return Ture if a string ends with the given suffix otherwise returns False.


ex:01
[source,python]
----
s = "python"
 print(s.endswith("N")) #it will give you false becouse it cap case
 print(s.endswith("p")) #it's correct (here you can check with spcae also)

----
=== string - isdigit( )

Isdigit return "True" if all characters in the string are digits, otherwise, it returns "False".

ex:01
[source,python]
----
s = "1234563211"
  print(s.isdigit())# Ture


a = "123321a"
  print(a.isdigit())# False
----


=== string - isalpha( )

isalpha return "True" if all characters in the string are alphabets, otherwise, it returns "False".


ex:01
[source,python]
----
s = "abcdfegk"
  print(s.isalpha())# Ture

a = "abcd321a"
  print(a.isalpha())# False (even if its space also given False)
----


=== string - isalnum( )

isalnum return "True" if all characters in a given string are alphabets or numeric oe alphanumeric, otherwise, it returns "False".


ex:01
[source,python]
----
s = "abc"
  print(s.isalnum())# Ture

a = "321"
  print(a.isalnum())# Ture

i = "321#213"
  print(a.isalnum())# False

----

=== List Datastructures

----
print(dir(list))
----

Nested list : we can crate list in side other list


ex:01
[source,python]
----

#    0   1  2     3        4  5
#    0   1  2[  0     1  ] 4  5
l = [10,20,30,["sai","ram"],40,50]

 print(l(3))
 print(l(11))
----



=== list slicing and indexing..
ex:01
[source,python]
----
l = [10,20,30,40,50]
 print(l(3:4))
 print(l(11))
----

=== Changing and adding element to list
ex:01( update / replace)
[source,python]
----
#    0  1  2  3  4
l = [10,20,30,40,50]
  print(l)

l[1]=33 # here 1 is index and 33 is value
  print(l)

----
ex:01( insert  )
[source,python]
----
#    0  1  2  3  4
l = [10,20,30,40,50]
  print(l)

l.insert(1,33) # here we can insert value for 1 index
  print(l)

----

append and expend : append is for only one value at a time and expend is used add multiple value to the method. at the end of the list

ex:01 (append and expend)

[source,python]
----
l = [10,20,30,40,50]
  print(l)

l.append(80)
  print(l)

l.extend(["ram","raj",12,12.5])
  print(l)
----

=== Delete or remove element from list

ex:01

[source,python]
----
l = [10,20,30,40,50]
  print(l)

l.remove(20) # value method we can remove the value
  print(l)

l.pop(4) # to remove using index method
 print(l)

l.clear()
 print(l)# if you want to delete only item from the list, we can add value later


del l
 perint(l) # to delete l list
----


=== list sort
sort is the build in funcation, by default and its arrang items in ascending order


ex:01

[source,python]
----
l = [1,2,3,4,5,6,7,8,9]

  print(l)
l.sort(l)
l.sort(reverse=Ture)
----


=== list copy
shallow copy and deep copy two types

ex:01

[source,python]
----
l = [1,2,3,4,5,6,7,8,9]

l1 = l
 print(l1) #shallow copy (it depend on first copy (l))


l1 = l.copy
 print(l1) #shallow copy (it depend on first copy (l))


l1.append(14)

 print(l1)#deep copy (it will not effect on first copy (l1))

----
=== list count and index


 Count is used to find number of values(occurrence)

ex:01

[source,python]
----
l = [1,2,3,4,5,2,7,8,3,4,9,4,7,6,2,1,4,0,6,7]

  print(l.count(2))# count
  print(l.count(7))
  print(l.count(0))

  print(l.index(2))#index
  print(l.index(7))
  print(l.index(0))

----

=== Creating List from user input values

ex:01

[source,python]
----
l = []

item1 = int(input("Enter int value:"))
item2 = input("Enter string value:")
item3 = float(input("Enter float value:"))


l.append(item1)# here only one value is possible
l.append(item2)
l.append(item3)

print(l)

l1 = []

l1.extend(item1,item2,item3)# here we can add multiple values

print(l1)


----



=== Creating List using range function

ex:01

[source,python]
----
l = []

n = int(int("Enter length of the list:"))

for i in range(n):
  x = int(input("Enter the value:"))
  l.append(x)

print(l)

print(list(range(2,10,3)))

print(list(range(10)))
----


=== tuple Datastructures

=== len(), max(), min(), sum()


==== Converting a string into tuple

ex:01

[source,python]
----
s = "coludcatayist"
 print(s)
 print(type(s))

t=tuple(s)
 print(t)
 print(type(t))

----

==== Converting a list into tuple

ex:01

[source,python]
----
s = "10,20,30,40"
 print(s)
 print(type(s))

t=tuple(s)
 print(t)
 print(type(t))

----


==== Converting tuple into string



=== tuple packing and unpacking

ex:01

[source,python]
----
a = 10
b = 20
c = 30
d = 40

t = a,b,c,d

print(t) # packing
print(type(t))

t = (10,20,30)

a,b,c,d = t
 print("a=",a)
 print("b=",b)
 print("c=",c)
----


// take a string any thing
//
// ouput = print even position charters and odd position characters saparate.
//
//      0123456789
// s = "ptyojnkjsd"
//
// s = "pythonisgood"
//
// print("Even position characture:",s[0::2])
// print("Odd position characture:",s[0::1])
//
//
// or

=== Set Datastructures

1. Set not have any index becouse set is un-order

===  How to change set ( add and update)
ex:01

[source,python]
----
S = {} # its dic not set
s1 = set() # to create empty set
s2 = {10,20,30,10,45.5,"python"}
  print(s)# it will remove duplicate value
  print(type(s))
----

=== add and update in set
. add is used to update only one value
. update will allow multiple value to set

ex:01

[source,python]
----
s2 = {10,20,30,10,45.5,"python"}

 print(s2)

s2.add(98) # only one value to set use `add`

  print(s2)

s2.update(23,"cloud")

  print(s2) # multiple value to add use `update`
----

=== Remove elements form set (discard(), remove(), clear() and del() )


ex:01

[source,python]
----
s2 = {10,20,30,10,45.5,"python"}

 print(s2)

s2.discard(100)
  print(s2) # it will not give any error if that value is not persent in discard.


s2.remove(100)
  print(s2) #keyerror - if value is not there in set


s3 = {10,20,30,10,45.5,"python"}

 print(s3)

s3.clear() # will clear all value in set(total set as empty)
  print(s3)

----

=== Set Operation { union(|), intersection(&), difference(-), symmetric difference(^) }
. union


ex:01

[source,python]
----
a = {1,2,3,4,5,6,7}
b = {8,9,7,6,5,4,1}
 print(a|b) # union
print(a.union(b))


c = {1,2,3,4,5,6,7}
d = {8,9,7,6,5,4,1}
 print(c&d) # intersection
 print(c.intersection(d))

e = {1,2,3,4,5,6,7}
f = {8,9,7,6,5,4,1}
 print(e-f) # difference
 print(e.difference(f))


g = {1,2,3,4,5,6,7}
h = {8,9,7,6,5,4,1}
 print(g^h) # symmetric_difference
 print(g.symmetric_difference(h))
----


=== membership test

ex:01

[source,python]
----
a = {1,2,3,4,5,6,7}

 print(100 in a) # membership test ( to check number is there or not )

----


=== len( ), max( ), min( ) and sum( )

ex:01

[source,python]
----
# coming soon
----

=== Dictionary Datastructures

1. what is dictionary ?
2. Creating dictionary
3. access



ex:01

[source,python]
----

d = {}

  print(d)
  print(type(d))

d1 = {1:"python", 2.1:"is", id:"easy",(1,2,3):"to",4:"learn"}

   print(d1(1))
   print(d1.get(1))
----

=== change or update

ex:01

[source,python]
----

d1 = {1:"python", 2.1:"is", id:"easy",(1,2,3):"to",4:"learn"}
d1["id"]="slno"
   print(d1) # if there is no key and value then that it will update new key value


#delete

d = {1:"python", 2.1:"is", id:"easy",(1,2,3):"to",4:"learn"}

  print(d)

del d["id"]
  print(d) # to delete perticulr key value


del d
  print(d) # to delete hole dic

# copy

d = {"id":"1235", "name":"python"}
d1=d.copy()

d1=["id"]=4355
 print(d1)


# items, key, value

d = {"id":"1235", "name":"python", "age":15}

  print(d)
  print(d.items())
  print(d.values())
  print(d.keys())


# membership test

d = {"id":"1235", "name":"python", "age":15}

 print(d)

 print("id" in d) # here we can check key only not for value it not possiable

# len

d = {"id":"1235", "name":"python", "age":15}

 print(d)
 print(len(d))

# pop


d = {"id":"1235", "name":"python", "age":15}

 print(d)

d1=d.pop("name") # delete using key

 print(d1)

#popiteam


d = {"id":"1235", "name":"python", "age":15}

 print(d)

d1=d.popitem()# last key:value will be deleted

 print(d1)
----


=== bytes
bytes is used to represent byte number just like an array the only allowed value for bytes is 0 to 256, and bytes is immuyable(we cant change).


=== bytearray

bytearray is used to represent byte number just like an array that only allowed values for bytearray is 0 to 256 and bytearray is mutable (we can change)


=== frozenset
 frozenset is mutable(we cant change)



== Function in python:

A function in Python is a reusable block of code that performs a specific task. It is defined using the def keyword followed by the function name and parentheses () which may include parameters. Functions help in organizing code, making it more readable, and avoiding repetition.


=== two type functions

1. perdefined function

 ex: print(),input(),type(),id()

2. userdefined function

----

import keyword
print(keyword.kwlist)
----

ex: syntax for function
[source,python]
----
def function_name(parameters): #parameters are input values
     '''docstring''' # distribution for funcation
     statements  # main task or any logic
     return statement # return is keyword that gives some output
----

ex:01
[source,python]
----
def f1():
  print("hello")

f1()
--
def f2():
    for i in range(100):
        print("hello")
--
def f5():
  pass # we can skip that function
--
def f6(name):
    print("hello:",name)

f6("coludcatayist")
---
def f7(n):
    print("square of",n, "is",n*n)
f7(5)
---
def add(a,b):
    print("sum is:",a+b)

add(5,20)
add(11.2,65.78)
---
a = int(input("Enter num1:")) # giving value at run time
b = int(input("Enter num2:")) # giving value at run time
def add(a,b):
    print("sum is:",a+b)
--or--
a = int(input("Enter num1:")) # giving value at run time
b = int(input("Enter num2:")) # giving value at run time

add(a=int(input("Enter num1:")),b=int(input("Enter num2:")))
---
def iseven(x):
     if x%2==0
        print(x, "is Eeven")
     else:
        print(x, "is odd")
iseven(3)
iseven(4)
----
ex:
[source,python]
----
def add(a,b):
    #print("sum is:", a+b)
    return a+b #


print("sum is:",add(20,60))
r = add(20,60)

def sub(r,c)
    print("sub is:",r-c)


sub(r,6)


----

==== single function can retrun multiple values


ex:
[source,python]
----
def sum_sub(a,b):
    sum=a+b
    sub=a-b
    mul=a*b
    return sum,sub,mul


x,y,z= sum_sub(10,20)

print("Sum is:",x)
print("Sub is:",y)#this is not good pratices
print("mul is:",z)# here we can do only sum or mul or sub (like addition only)
----

ex:
[source,python]
----
def sum(a,b)
     return a+b

def sub(a,b)
    return a-b


def mul(a,b)
    return a*b

x=sum(10,20)
y=sub(30,20)
z=mul(20,10)

print("Sum is:",x)
print("Sub is:",y)
print("mul is:",z)

----
=== Types of variables in funcation (local and global variables)

1. Local variables:

The variables which are declare inside the function and that variables are only available to thet  function is called local variables.

local variables can't access outside the funcation


ex:
[source,python]
----
def f1():
    a=10
    print(a)

def f2():
    b=20
    print(b)
    print(a)# here we cant use `a` that variable is not define in this function

f1()
f2()

----


==== 2. Global variable:

The variables which are declare outside the function and that variables are only available to all function in the program is called global variables.


==== Global keyword

Global key is used to make global variable available to a particular function for required modification.
----
import keyword
print(keyword.kwlist)# to print all keyword in python
----
ex:
[source,python]
----
a=10#this are global variables
b=20# it available to access not for modification.

def f1():
    print(a)

def f2():
    print(b)

f1()
f2()

----


ex:
[source,python]
----
a=10

def f1():
    global a
    a=99
    print(a)

def f2():
    print(a)


f1()
f2()
----

ex:
[source,python]
----
a=10

def f1():
    a=99 # here local and globale variable both are same then first perferance is local variable
    print(a)
    print(globals()['a']) # here am calling global variable

def f2():
    print(a)


f1()
f2()
----

=== Different type of arguments(paraments)

==== There are four types of arguments

- positional arguments
- keyword arguments
- default arguments
- variable length arguments


==== 1. positional arguments

The argument which are passed to a function in correct positional order is called positional arguments

if we change order or position then result may change, if we increase or decrease the no of arguments then we get error.


ex:
[source,python]
----
def add(a,b):
    print(a-b)

sub(10,20) # here a,b are formal arguments and 10,20 are actual arguments
sub(20,10) # ex: sub(10,20,30) and sub(10) here check the definition

----


==== 2. keyword arguments

The arguments which are passed to a function with keyword or parameter name is called keyword arguments.

while working with keyword arguments the order or position is not important but keyword are important.

ex:
[source,python]
----

def f1(name,msg):
    print("Hello:",name,msg)

#keyword args
f1(name="chiru",msg="Good Morning")
f1(msg="Good Morning",name="chiru")# here if i change order result will be same


#positional args
f1("chiru","Good Morning")
f1("Good Morning","chiru")# here there based on order you will get

#one  positional and one keyword args
#make sure that first we have to mention positional args then after keyword args

f1("chiru",msg="Good Morning") #correct
f1(name="chiru","Good Morning") #wrong (error will occure)
----

==== 3. default arguments

if you dont set any args,

function with default value will take that value

ex:
[source,python]
----
def f1(course="python"): # here i define default value as python
    print("course is:",course)

f1("c")

f1("java")

f1() # here am not given any args so it will take default value to the parameter

# one default one non default argument, make sure that first non default argument and then after default argument
def f2(course="python",name): # here i define default value as python
    print(name,"course is:",course)

f2("java","sumanth") #here we need to pass non default args first
f2("chiru","c") # correct
f2("chiru") # here i define default value as python
----

==== 4. variable length arguments

some time we can call a function with multiple values including zero(0) value
ex:
[source,python]
----
def f1(*a): # here `*` is most important for variable args
    print(a)

f1()
f1(10)
f1(10,20)
f1(10,20,30)
f1(10,20,30,40,50)


----

ex:
[source,python]
----
def add(*n):
    s=0
    for i in n:
        s=s+i
    print("Sum is:",s)

add()
add(10)
add(10,20)
add(10,20.2,0,995,65.45)
----


IMPORTANT: Interview Question ( What is `*args` and **kwargs ?)
----
*args allows us to pass no zero(0) value to the function including zero +
*args will store the value in tuple formate +
**kwargs allow us to pass no of keyword arguments to the funcation +
**kwargs will store the values in dict formate+
----

ex:
[source,python]
----
def f1(**kwargs):
    for k,v in kwarges,items():
        print(_k_,"=",v)

f1(a=20,b=20,c=30)
f1(eid=125,ename="chiru",eaddress="bang")


----

next video 17