== Python

Python was designed and developed by Guido Van Rossum.
The name comes from the Monty Python's Circus show on the BBC.
Official website: http://www.python.org

Python is a programming language used to write the coding part for application development.

== Django

Django is a web application development framework used to design and develop websites.

== Python Features

Python is a general-purpose, high-level, interpreted, dynamically typed, and case-sensitive programming language.

- *High level*: No need to manage memory and security-related aspects; these are handled by default.
- *Interpreted*: Python and JavaScript are interpreted languages, meaning they check and execute code line by line. They are also **dynamically typed**.

Example of dynamically typed:

ex:

    datatype varibalename=value
    a=10

- *Compiler-based*: Group of lines (the whole program code) are checked once and executed. These are **statically typed** languages. Examples include Java, C, C++, C#, and .NET.

Example of statically typed:

ex:

 datatype variablename = value;
 int x = 10;

why python?

huge standard libraries

NOTE: **immutable** : cannot change and **mutable** : can change



== Application area of python:

1. Standalone or desktop app -  console App(CUI) and Desktop GUI
2. web application(Django framework or flask)
3. Databased application
4. Gaming application
5. Data analysis (Datascience)
6. Statistical analysis
7. Testing, AI, ML, Devops, IOT, Business app, Network programming.

== Features of Python

. Simple and easy to learn
. Free and Open Source
. High Level
. Platform Independent (cross-platform)
. Portability ( one platform(windows) to other(linux) platform shift easy)
. Dynamically typed
. Procedure and object-oriented
. Extensible and Extensive library


== Different ways t write python script and execute:

1. Using Interactive mode
2. Using script mode(.py)
3. Using python IDLE
4. Using Pycharm editor


== Fundamental Concepts

1. Comments in python

- Single line comment

ex:
[source,python]
----
#this is single line comment
This is un-comment line
----

- Multi line comment

ex:
[source,python]
----
'''
this is multi line
comment example
'''
this is un-comment line
----

2. Keywords and reserved words

keyword is library and this keyword are reserved form python, keywords cant be used as variable or personal use case.

ex:
[source,python]
----
import keyword
print(keyword.kwlist)
----

Output:

  ['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


3. Indentation


4 spaces

4. Identifiers

- Rule to define Identifier
. lowercase or Uppercase (ex:01)
. case sensitive
. allow digits(0-9) it should not Start with digits (ex:02)
. should not be two parts (ex:03)
. allow underscore(_)
. if an identifier starts with underscore then it is private
. we cant use any keyword or reserved word as identifier (ex:04)


ex:01
[source,python]
----
empid = 1234
   print(EMPID) # This is wrong it should be match with variable
   print(empid) # This is correct
----
NOTE: Always use lowercase for best pratices

ex:02
[source,python]
----
empid01 = 1234
01empid = 1234
   print(empid01) # This is correct
   print(01empid)  # This is wrong it should not start with digits
----

(ex:03)
[source,python]
----
emp id = 1234
empid = 1234
   print(emp id) # This is wrong it should not be two parts
   print(empid) # This is correct
----

(ex:04)
[source,python]
----
def = 1234
deff = 1234
   print(deff) # This is correct
   print(def) # This is wrong it should not keyword or reserved word as identifier
----


5. Variables

. Variable is also consider as identifier
. variable is a named memory location
. while declaring the variable in python we needd not specify any datatype because python is dynamically typed programming languages
. based on the value datatype will decide implicitly

(ex:01)
[source,python]
----
a = 1234
b = 10.9
c = "s"
   print(a)
   print(type(a)
   print(b)
   print(type(b)
   print(c)
   print(type(c)
----

6. Multiple assignment

. Is the process of assigning the multiple value to multiple variables (ex:01)
. Is the process of assigning a single value to multiple variables (ex:02)


ex:01
[source,python]
----
a,b,c=10,20,30
    print(a,end=",")
    print(b,end=",")
    print(c) # here there is value for c attribute so we cant use end attribute for `c` value

----

ex:02
[source,python]
----
a = b = c = 10
   print(a,b,c) #or
   print(a)
   print(b)
   print(c)
   print(a,b,c,sep=":")
----


== DataTypes

Datatype is used to represent what type of values are going to store inside the variable.

=== Basic Datatype
// . None
// . Numeric
// - int
// - float
// - bool
// - complex
//
// . Sequence Datatype:
//
// -  String
// -  list
// - tuple
// - set
// - dict
// - range
// - bytes
// - bytearray
// - fronzenset

|===
| Basic Datatype | Description

| None(ex:01)
| Represents the absence of a value

| Numeric
| Represents numeric values

| int (ex:02)
| Integer numbers (e.g., -1, 0, 42)

| float (ex:02)
| Floating-point numbers (e.g., 3.14, -0.001)

| bool
| Boolean values (True or False)

| complex
| Complex numbers with a real and imaginary part

| Sequence Datatype
| Description

| String
| Ordered collection of characters (immutable)

| list
| Ordered collection of items (mutable)

| tuple
| Ordered collection of items (immutable)

| set
| Unordered collection of unique items

| dict
| Collection of key-value pairs

| range
| Sequence of numbers commonly used for looping

| bytes
| Sequence of integers representing raw binary data (immutable)

| bytearray
| Mutable sequence of integers representing binary data

| frozen set
| Immutable set of unique items

|===



ex:01
[source,python]
----
a = None #in python
b = null #in other langauges
  print(a)
  print(b)
  print(type(a))
  print(type(b)) # you will get error and difference for python and other langauges
----


ex:02
[source,python]
----
c = 10 # int
d = 5.5  # float
  print(c)
  print(d)
  print(type(c))
  print(type(d))

# how to convert int to float

e = float(c)
 print(e)
 print(type(e)) # converted `int to float`

 # how to convert   float to int

f = int(d)
 print(f)
 print(type(f)) # converted ` float to int`
----

ex:
[source,python]
----
name = " raju "
  print("your name is:",name)   #
name = input("Enter your Name:")  # run time inputs
  print("your name is:",name)
  print(type(name))
----


ex:
[source,python]
----
a = input("Enter A number:") # by default it will take as string so you need change to int
 print(type(a))
x = int(a)
 print(type(a))
b = input("Enter B number:") # by default it will take as string so you need change
 print(type(b))
y = int(b)
 print(type(y))
c = a+b
z = x+b
print(The result is:",c)
print(The result is:",z)
#output
#1020

----
NOTE: All inputs are taken as strings by default; explicit conversion is required for other data types. Conversion mechanism only for runtime execution

ex:
[source,python]
----
a = input(Enter Num1:")
b = input(Enter Num2:")
 print("result is:",a+b)

x = float(input(Enter Num1:"))
y = float(input(Enter Num2:"))
 print("result is:",x+y)
----

====  bool Datatype

only allowed value True as 1 and False as 0

ex: 01
[source,python]
----
a = 10
b = 20
c=a<b  #True
d=a>b  #False
 print(C)
 print(d)
 print(type(c))
 print(type(d))
 print(True+True)
 print(True+9)
----

==== complex
a+bj # j is imagernay numbers
ex:01
[source,python]
----
a=2
b=3
c=complex(a,b)
 print(c)
 print(type(c))
 print(c.real) # To print real and imagenary values
 print(c.imag)  # To print real and imagenary values 
----

ex:02
[source,python]
----
a=2+3j
b=5+2j
 print(a+b)
----


==== Sequence Datatype

**String**   :  String is a sequence of characters or group od character string can be represented with string and string can be created by using '' or "" or '''  ''' or """ """




print(dir(list))


help(str) #any str like list, tuple


**list** :

. List is ordered collection of elements
. list can be created by using []
. List will allow duplicate elements
. List contains different datatype elements
. List is mutable, once we create wa list that can change

ex:01
[source,python]
----
l = [10,20,30,"a",20,50]
  print(l)
  print(type(l))
----
**tuple** :

. tuple is ordered collection of elements
. tuple can be created by using () but brackets are optional
. tuple will allow duplicate elements
. tuple contains different datatype elements
. tuple is immutable, once we create a tuple that cannot be change

NOTE: To create tuple with single element, after element we should give comma(,)

ex:01
[source,python]
----
t = (10,) #here for single element
  print(t)
  print(type(t))

----


ex:02
[source,python]
----
t = (10.0, 10, 20, "xyz", 'a', 23)
  print(t)
  print(type(t))
----


**set** :

. set is unordered collection of unique element.
. set can be create by using { }.
. set contains differnet datatype elements.
. set is mutable once we create a set that can be modify.
. set will not allow duplicate values.