= Terraform Overview

== Q1. What do you understand by Terraform in AWS?
Terraform is a part of the AWS DevOps Competency and is also an AWS Partner Network (APN) advanced technology partner. It is similar to AWS CloudFormation in the sense that it is also an “infrastructure as code” tool that allows you to create, update, and version your AWS infrastructure.

== Q2. What are the key features of Terraform?
Terraform helps you manage all of your infrastructure as code and construct it as and when needed. Here are its key main features:
- A console that allows users to observe functions
- The ability to translate HCL code into JSON format
- A configuration language that supports interpolation
- A module count that keeps track of the number of modules applied to the infrastructure.

== Q3. Define IAC?
IAC or Infrastructure as Code allows you to build, change, and manage your infrastructure through coding instead of manual processes. The configuration files are created according to your infrastructure specifications, and these configurations can be edited and distributed securely within an organization.

== Q5. What are the most useful Terraform commands?
Some of the most useful Terraform commands are:
- `terraform init` - initializes the current directory
- `terraform refresh` - refreshes the state file
- `terraform output` - views Terraform outputs
- `terraform apply` - applies the Terraform code and builds stuff
- `terraform destroy` - destroys what has been built by Terraform
- `terraform graph` - creates a DOT-formatted graph
- `terraform plan` - a dry run to see what Terraform will do

== Q6. Are callbacks possible with Terraform on Azure?
By using the Azure Event Hubs, callbacks are possible on Azure. Terraform’s Azure provider offers effortless functionality to users. Microsoft Azure Cloud Shell provides an already-installed Terraform instance.

== Q7. What is Terraform init?
`terraform init` is a command to initialize an operational directory that contains Terraform configuration files. This command can be run multiple times. It is the first command that should be executed after writing new Terraform configurations.

== Q8. What is Terraform D?
`Terraform D` is a plugin used on most in-service systems and Windows. `terraform init` by default searches the following directories for plugins.

== Q9. Is history the same as it is on the web while using TFS API to provide resources?
Yes, the history is similar to what is available on the web because the UI relies on the API as the base. The information displayed in the UI is available through other methods and the API.

== Q10. Why is Terraform used for DevOps?
Terraform uses a JSON-like configuration language called HashiCorp Configuration Language (HCL). HCL has a very simple syntax that makes it easy for DevOps teams to define and enforce infrastructure configurations across multiple clouds and on-premises data centers.

== Q11. Define null resource in Terraform.
`null_resource` implements the standard resource library, but no further action is taken. The `triggers` argument allows an arbitrary set of values that will cause the replacement of resources when changed.

== Q12. What do you mean by Terraform Cloud?
Terraform Cloud is a platform that enables teams to use Terraform together, either on-demand or in response to various events. It is deeply integrated with Terraform's workflows and data, unlike a general-purpose continuous integration system. It includes easy access to shared state and secret data, detailed policy controls for updating infrastructure and governing the contents of Terraform, a private registry for sharing Terraform modules, and much more.

== Q13. What do you understand by the terraform backend?
Each Terraform configuration can specify a backend, which defines two main things:
- Where operations are performed
- Where the state is stored (Terraform keeps track of all the resources created in a state file)


== Q13. What are the version controls supported by Terraform besides GitHub?
The version controls supported by Terraform include:
- GitLab EE
- GitLab CE
- Bitbucket Cloud

== Q14. Name some major competitors of Terraform.
Some of the top competitors and alternatives to Terraform are:
- Azure Management Tools
- Morpheus
- CloudHealth
- Turbonomic
- CloudBolt

== Q15. Explain the uses of Terraform CLI and list some basic CLI commands.
The Terraform Command-Line Interface (CLI) is used to manage infrastructure and interact with Terraform state, configuration files, providers, etc. Here are some basic CLI commands:
- `terraform init` - initializes the current directory
- `terraform refresh` - refreshes the state file
- `terraform output` - views Terraform outputs
- `terraform apply` - applies the Terraform code and builds stuff
- `terraform destroy` - destroys what has been built by Terraform
- `terraform graph` - creates a DOT-formatted graph
- `terraform plan` - a dry run to see what Terraform will do

== Q16. What are modules in Terraform?
A module in Terraform is a container for multiple resources that are used together. The root module includes resources defined in the `.tf` files and is required for every Terraform configuration.

== Q17. What is a Private Module Registry?
A Private Module Registry is a feature from Terraform Cloud that allows users to share Terraform modules across the organization. You can enforce rules or “Sentinel policies” on the registry that specify how members of your organization can use the modules.

== Q18. Is Terraform usable for on-prem infrastructure?
Yes, Terraform can be used for on-prem infrastructure. With a variety of available providers, you can choose the one that best suits your needs. All that is required is an API.

== Q19. Does Terraform support multi-provider deployments?
Yes, Terraform supports multi-provider deployments, including on-premises solutions like OpenStack and VMware. Terraform can also manage Software-Defined Networking (SDN).

== Q20. How is duplicate resource error ignored during terraform apply?
To handle duplicate resource errors, you can try the following options:
- Delete those resources from the cloud provider (API) and recreate them using Terraform.
- Remove those resources from the Terraform code to stop managing them.
- Perform a `terraform import` of the resource and remove the code that is trying to recreate them.

== Q21. What are the various version controls supported by Terraform?
The supported version controls are:
- Azure DevOps Services
- Azure DevOps Server
- Bitbucket Server
- Bitbucket Cloud
- GitLab EE and CE
- GitLab.com
- GitHub Enterprise
- GitHub.com (OAuth)
- GitHub.com

== Q22. What are some of the built-in provisioners available in Terraform?
Here is the list of built-in provisioners in Terraform:
- Salt-masterless Provisioner
- Remote-exec Provisioner
- Puppet Provisioner
- Local-exec Provisioner
- Habitat Provisioner
- File Provisioner
- Chef Provisioner

== Q23. Which command destroys Terraform managed infrastructure?
The command used for this purpose is:
`terraform destroy [options] [dir]`

== Q24. Tell us about some notable Terraform applications.
The applications of Terraform are broad due to its capability to extend its abilities for resource manipulation. Some notable applications are:
- Software demos development
- Resource schedulers
- Multi-cloud deployment
- Disposable environment creation
- Multi-tier application development
- Self-service clusters
- Setup of Heroku App

== Q25. What are the components of Terraform architecture?
The Terraform architecture includes the following components:
- Sub-graphs
- Expression Evaluation
- Vertex Evaluation
- Graph Walk
- Graph Builder
- State Manager
- Configuration Loader
- CLI (Command Line Interface)
- Backend

== Q26. Define Resource Graph in Terraform.
A resource graph is a visual representation of the resources. It helps modify and create independent resources simultaneously. Terraform uses the resource graph to generate plans and refresh the state, creating structure most efficiently to help understand dependencies and potential issues.

== Q27. Can you provide a few examples where Sentinel policies can be used?
Sentinel policies are a powerful way to implement various policies in Terraform. Here are a few examples:
- Enforce explicit ownership in resources
- Restrict roles the cloud provider can assume
- Review an audit trail for Terraform Cloud operations
- Forbid only certain resources, providers, or data sources
- Enforce mandatory tagging on resources
- Restrict how modules are used in the Private Module Registry

== Q28. What are the various levels of Sentinel enforcement?
Sentinel has three enforcement levels:
- Advisory: Logged but allowed to pass. An advisory is issued to the user when they trigger a plan that violates the policy.
- Soft Mandatory: The policy must pass unless an override is specified. Only administrators have the ability to override.
- Hard Mandatory: The policy must pass no matter what. This policy cannot be overridden unless it is removed. It is the default enforcement level in Terraform.



== Q27. How to Store Sensitive Data in Terraform?

Terraform requires credentials to communicate with your cloud provider's API. But most of the time, these credentials are saved in plaintext on your desktop. GitHub is exposed to thousands of API and cryptographic keys every day. Hence, your API keys should never be stored in Terraform code directly. You should use encrypted storage to store all your passwords, TLS certificates, SSH keys, and anything else that shouldn't be stored in plain text.

== Q28. What is Terragrunt, and what are its uses?

Terragrunt is a thin wrapper that provides extra tools to keep configurations DRY, manage remote state, and work with multiple Terraform modules. It is used for:
* Working with multiple AWS accounts
* Executing Terraform commands on multiple modules
* Keeping our CLI flags DRY
* Keeping our remote state configuration DRY
* Keeping our Terraform code DRY

== Q29. Explain State File Locking

State file locking is a Terraform mechanism in which operations on a specific state file are blocked to avoid conflicts between multiple users performing the same process. When one user releases the lock, then only the other one can operate on that state. This helps in preventing state file corruption. This is a backend operation.

== Q30. What do you understand by a Tainted Resource?

A tainted resource is a resource that is forced to be destroyed and recreated on the next command. When a resource is marked as tainted, the state files are updated, but nothing changes on the infrastructure. The `terraform plan` shows that it will be destroyed and recreated. The changes get implemented when the next `terraform apply` happens.

== Q31. How to lock Terraform module versions?

A proven way of locking Terraform module versions is using the Terraform module registry as a source. We can use the `version` attribute in the module of the Terraform configuration file. As the GitHub repository is being used as a source, we need to specify versions, branch, and query strings with `?ref`.

== Q32. What is Terraform Core?

Terraform Core is a binary written statically compiled by using the Go programming language. The compiled binary offers an entry point for the users of Terraform. The primary responsibilities include:
* Reading and interpolation of modules and configuration files by Infrastructure as code functionalities
* Resource Graph Construction
* Plugin communication through RPC
* Plan execution
* Management of resource state

== Q33. Give the Terraform configuration for creating a single EC2 instance on AWS.

This is the Terraform configuration for creating a single EC2 instance on AWS:

[source,hcl]
----
provider "aws" {
  region = ""
}

resource "aws_instance" "example" {
  ami           = "ami-213123585"
  instance_type = "t2.micro"

  tags = {
    Name = "example"
  }
}
----

== Q34. How will you upgrade plugins on Terraform?

Run `terraform init` with the `-upgrade` option. This command rechecks the releases.hashicorp.com to find new acceptable provider versions. It also downloads available provider versions. `.terraform/plugins/_` is the automatic downloads directory.

== Q35. How will you make an object of one module available for the other module at a high level?

An output variable is defined in resource configuration. Declare the output variable of `module_A`. Create a file `variable.tf` for `module_B`. Establish the input variable inside this file having the same name as the key defined in `module_B`. Replicate the process for making variables available to other modules.

== Q36. What are some of the latest Terraform Azure Provider factors?

The latest versions involve new data resources and `azurerm_batch_certificate`, which helps in managing the certificate. This resource is used for controlling the prefix in networking. There are fixes for bugs, and `azurerm_app_service` has also been enhanced.

== Q37. How will you control and handle rollbacks when something goes wrong?

I need to recommit the previous code version to be the new and current version in my VCS. This would trigger a Terraform run, which would be responsible for running the old code. As Terraform is more declarative, I will make sure all things in the code roll back to the old code. I would use the State Rollback Feature of Terraform Enterprise to roll back to the latest state if the state file got corrupted.
